(defun create-double-nan () (cl::%make-double-float #x7FF8000000000000))
(defun create-double-pos-inf () (cl::%make-double-float #x7FF0000000000000))
(defun create-double-neg-inf () (cl::%make-double-float #xFFF0000000000000))
(defun create-single-nan () (cl::%make-single-float #x7Fc00000))
(defun create-single-pos-inf () (cl::%make-single-float #x7F800000))
(defun create-single-neg-inf () (cl::%make-single-float #xFF800000))
(defun create-short-nan () (cl::%make-short-float #x1FF00000))
(defun create-short-pos-inf () (cl::%make-short-float #x1FE00000))
(defun create-short-neg-inf () (cl::%make-short-float #x3FE00000))


(setf ad (create-double-nan)
	  bd (create-double-pos-inf)
	  cd (create-double-neg-inf)
	  af (create-single-nan)
	  bf (create-single-pos-inf)
	  cf (create-single-neg-inf)
	  as (create-short-nan)
	  bs (create-short-pos-inf)
	  cs (create-short-neg-inf)
	  xx nil)
