//		-------------------------------
//		Copyright (c) Corman Technologies Inc.
//		See LICENSE.txt for license information.
//		-------------------------------
//
#ifndef HELPIDS_H
#define HELPIDS_H

#define IDH_CORMANLISP_TIMEDATE		1001

#define IDH_CORMANLISP_ALIGN			1003
#define IDH_CORMANLISP_TABSET		1004
#define IDH_CORMANLISP_TABCLEAR		1005
#define IDH_CORMANLISP_TAB_CLEARALL	1006
#define IDH_CORMANLISP_TABSTOPS		1007
#define IDH_CORMANLISP_TEXTFILE		1008
#define IDH_CORMANLISP_FORMATTED		1009

#define IDH_CORMANLISP_WORD6FILE		1017
#define IDH_CORMANLISP_FILENEW_DOC	1018
#define IDH_CORMANLISP_OPTIONS_AUTOWORDSEL	1019

#define IDH_CORMANLISP_INDENT_LEFT	1020
#define IDH_CORMANLISP_INDENT_RIGHT	1021
#define IDH_CORMANLISP_INDENT_FIRST	1022

#define IDH_CORMANLISP_WRAP_NO		1023
#define IDH_CORMANLISP_WRAP_WINDOW	1024
#define IDH_CORMANLISP_WRAP_RULER	1025

#define IDH_COMM_GROUPBOX			1026

#define IDH_CORMANLISP_INCHES		1027
#define IDH_CORMANLISP_CENTIMETERS	1028
#define IDH_CORMANLISP_POINTS		1029
#define IDH_CORMANLISP_PICAS			1030

#define IDH_CORMANLISP_CHECK_TOOLBAR	1031
#define IDH_CORMANLISP_CHECK_FORMATBAR	1032
#define IDH_CORMANLISP_CHECK_STATUSBAR	1033
#define IDH_CORMANLISP_CHECK_RULERBAR	1034

#define IDH_CORMANLISP_TOPMARGIN		1035
#define IDH_CORMANLISP_BOTTOMMARGIN	1036
#define IDH_CORMANLISP_LEFTMARGIN 	1037
#define IDH_CORMANLISP_RIGHTMARGIN	1038

#endif // HELPIDS_H