;;; vb\odbc-ffi.lisp -- Automatically generated FFI definition file.
;;; Source: vb\odbc-h.lisp
;;; Transcribed: 12:45 AM November 26, 1998 Eastern Standard Time

(MAKE-PACKAGE "ODBC" :USE '("COMMON-LISP" "C-TYPES"))
(IN-PACKAGE :ODBC)
(PROGN
    (EXPORT 'ODBCVER)
    (DEFCONSTANT ODBCVER 768)
    (EXPORT 'SQLCHAR)
    (C-TYPES:DEFCTYPE SQLCHAR :UNSIGNED-CHAR)
    (EXPORT 'SQLSCHAR)
    (C-TYPES:DEFCTYPE SQLSCHAR :CHAR)
    (EXPORT 'SQLDATE)
    (C-TYPES:DEFCTYPE SQLDATE :UNSIGNED-CHAR)
    (EXPORT 'SQLDECIMAL)
    (C-TYPES:DEFCTYPE SQLDECIMAL :UNSIGNED-CHAR)
    (EXPORT 'SQLDOUBLE)
    (C-TYPES:DEFCTYPE SQLDOUBLE :DOUBLE-FLOAT)
    (EXPORT 'SQLFLOAT)
    (C-TYPES:DEFCTYPE SQLFLOAT :DOUBLE-FLOAT)
    (EXPORT 'SQLINTEGER)
    (C-TYPES:DEFCTYPE SQLINTEGER :LONG)
    (EXPORT 'SQLUINTEGER)
    (C-TYPES:DEFCTYPE SQLUINTEGER :UNSIGNED-LONG)
    (EXPORT 'SQLNUMERIC)
    (C-TYPES:DEFCTYPE SQLNUMERIC :UNSIGNED-CHAR)
    (EXPORT 'SQLPOINTER)
    (C-TYPES:DEFCTYPE SQLPOINTER (:VOID *))
    (EXPORT 'SQLREAL)
    (C-TYPES:DEFCTYPE SQLREAL :SINGLE-FLOAT)
    (EXPORT 'SQLSMALLINT)
    (C-TYPES:DEFCTYPE SQLSMALLINT :SHORT)
    (EXPORT 'SQLUSMALLINT)
    (C-TYPES:DEFCTYPE SQLUSMALLINT :UNSIGNED-SHORT)
    (EXPORT 'SQLTIME)
    (C-TYPES:DEFCTYPE SQLTIME :UNSIGNED-CHAR)
    (EXPORT 'SQLTIMESTAMP)
    (C-TYPES:DEFCTYPE SQLTIMESTAMP :UNSIGNED-CHAR)
    (EXPORT 'SQLVARCHAR)
    (C-TYPES:DEFCTYPE SQLVARCHAR :UNSIGNED-CHAR)
    (EXPORT 'SQLRETURN)
    (C-TYPES:DEFCTYPE SQLRETURN SQLSMALLINT)
    (EXPORT 'SQLHANDLE)
    (C-TYPES:DEFCTYPE SQLHANDLE (:VOID *))
    (EXPORT 'SQLHENV)
    (C-TYPES:DEFCTYPE SQLHENV SQLHANDLE)
    (EXPORT 'SQLHDBC)
    (C-TYPES:DEFCTYPE SQLHDBC SQLHANDLE)
    (EXPORT 'SQLHSTMT)
    (C-TYPES:DEFCTYPE SQLHSTMT SQLHANDLE)
    (EXPORT 'SQLHDESC)
    (C-TYPES:DEFCTYPE SQLHDESC SQLHANDLE)
    (EXPORT 'UCHAR)
    (C-TYPES:DEFCTYPE UCHAR :UNSIGNED-CHAR)
    (EXPORT 'SCHAR)
    (C-TYPES:DEFCTYPE SCHAR :CHAR)
    (EXPORT 'SQLSCHAR)
    (C-TYPES:DEFCTYPE SQLSCHAR SCHAR)
    (EXPORT 'SDWORD)
    (C-TYPES:DEFCTYPE SDWORD :LONG)
    (EXPORT 'SWORD)
    (C-TYPES:DEFCTYPE SWORD :SHORT)
    (EXPORT 'UDWORD)
    (C-TYPES:DEFCTYPE UDWORD :UNSIGNED-LONG)
    (EXPORT 'UWORD)
    (C-TYPES:DEFCTYPE UWORD :UNSIGNED-SHORT)
    (EXPORT 'SQLUINTEGER)
    (C-TYPES:DEFCTYPE SQLUINTEGER UDWORD)
    (EXPORT 'SLONG)
    (C-TYPES:DEFCTYPE SLONG :LONG)
    (EXPORT 'SSHORT)
    (C-TYPES:DEFCTYPE SSHORT :SHORT)
    (EXPORT 'ULONG)
    (C-TYPES:DEFCTYPE ULONG :UNSIGNED-LONG)
    (EXPORT 'USHORT)
    (C-TYPES:DEFCTYPE USHORT :UNSIGNED-SHORT)
    (EXPORT 'SDOUBLE)
    (C-TYPES:DEFCTYPE SDOUBLE :DOUBLE-FLOAT)
    (EXPORT 'LDOUBLE)
    (C-TYPES:DEFCTYPE LDOUBLE :DOUBLE-FLOAT)
    (EXPORT 'SFLOAT)
    (C-TYPES:DEFCTYPE SFLOAT :SINGLE-FLOAT)
    (EXPORT 'PTR)
    (C-TYPES:DEFCTYPE PTR (:VOID *))
    (EXPORT 'HENV)
    (C-TYPES:DEFCTYPE HENV (:VOID *))
    (EXPORT 'HDBC)
    (C-TYPES:DEFCTYPE HDBC (:VOID *))
    (EXPORT 'HSTMT)
    (C-TYPES:DEFCTYPE HSTMT (:VOID *))
    (EXPORT 'RETCODE)
    (C-TYPES:DEFCTYPE RETCODE :SHORT)
    (EXPORT 'HWND)
    (C-TYPES:DEFCTYPE HWND :HANDLE)
    (EXPORT 'SQLHWND)
    (C-TYPES:DEFCTYPE SQLHWND HWND)
    (EXPORT '(DATE_STRUCT))
    (C-TYPES:DEFCSTRUCT
        DATE_STRUCT
        ((YEAR SQLSMALLINT)
            (MONTH SQLUSMALLINT)
            (DAY SQLUSMALLINT)))
    (EXPORT 'SQL_DATE_STRUCT)
    (C-TYPES:DEFCTYPE SQL_DATE_STRUCT DATE_STRUCT)
    (EXPORT '(TIME_STRUCT))
    (C-TYPES:DEFCSTRUCT
        TIME_STRUCT
        ((HOUR SQLUSMALLINT)
            (MINUTE SQLUSMALLINT)
            (SECOND SQLUSMALLINT)))
    (EXPORT 'SQL_TIME_STRUCT)
    (C-TYPES:DEFCTYPE SQL_TIME_STRUCT TIME_STRUCT)
    (EXPORT '(TIMESTAMP_STRUCT))
    (C-TYPES:DEFCSTRUCT
        TIMESTAMP_STRUCT
        ((YEAR SQLSMALLINT)
            (MONTH SQLUSMALLINT)
            (DAY SQLUSMALLINT)
            (HOUR SQLUSMALLINT)
            (MINUTE SQLUSMALLINT)
            (SECOND SQLUSMALLINT)
            (FRACTION SQLUINTEGER)))
    (EXPORT 'SQL_TIMESTAMP_STRUCT)
    (C-TYPES:DEFCTYPE SQL_TIMESTAMP_STRUCT TIMESTAMP_STRUCT)
    (EXPORT 'SQLINTERVAL)
    (C-TYPES:DEFCTYPE SQLINTERVAL :LONG)
    (EXPORT 'SQL_IS_YEAR)
    (DEFCONSTANT SQL_IS_YEAR 1)
    (EXPORT 'SQL_IS_MONTH)
    (DEFCONSTANT SQL_IS_MONTH 2)
    (EXPORT 'SQL_IS_DAY)
    (DEFCONSTANT SQL_IS_DAY 3)
    (EXPORT 'SQL_IS_HOUR)
    (DEFCONSTANT SQL_IS_HOUR 4)
    (EXPORT 'SQL_IS_MINUTE)
    (DEFCONSTANT SQL_IS_MINUTE 5)
    (EXPORT 'SQL_IS_SECOND)
    (DEFCONSTANT SQL_IS_SECOND 6)
    (EXPORT 'SQL_IS_YEAR_TO_MONTH)
    (DEFCONSTANT SQL_IS_YEAR_TO_MONTH 7)
    (EXPORT 'SQL_IS_DAY_TO_HOUR)
    (DEFCONSTANT SQL_IS_DAY_TO_HOUR 8)
    (EXPORT 'SQL_IS_DAY_TO_MINUTE)
    (DEFCONSTANT SQL_IS_DAY_TO_MINUTE 9)
    (EXPORT 'SQL_IS_DAY_TO_SECOND)
    (DEFCONSTANT SQL_IS_DAY_TO_SECOND 10)
    (EXPORT 'SQL_IS_HOUR_TO_MINUTE)
    (DEFCONSTANT SQL_IS_HOUR_TO_MINUTE 11)
    (EXPORT 'SQL_IS_HOUR_TO_SECOND)
    (DEFCONSTANT SQL_IS_HOUR_TO_SECOND 12)
    (EXPORT 'SQL_IS_MINUTE_TO_SECOND)
    (DEFCONSTANT SQL_IS_MINUTE_TO_SECOND 13)
    (EXPORT '(SQL_YEAR_MONTH_STRUCT))
    (C-TYPES:DEFCSTRUCT SQL_YEAR_MONTH_STRUCT ((YEAR SQLUINTEGER)
        (MONTH SQLUINTEGER)))
    (EXPORT '(SQL_DAY_SECOND_STRUCT))
    (C-TYPES:DEFCSTRUCT
        SQL_DAY_SECOND_STRUCT
        ((DAY SQLUINTEGER)
            (HOUR SQLUINTEGER)
            (MINUTE SQLUINTEGER)
            (SECOND SQLUINTEGER)
            (FRACTION SQLUINTEGER)))
    (EXPORT '(SQL_INTERVAL_STRUCT))
    (C-TYPES:DEFCSTRUCT
        SQL_INTERVAL_STRUCT
        ((INTERVAL_TYPE SQLINTERVAL)
            (INTERVAL_SIGN SQLSMALLINT)
            (INTVALDATA (SQLUINTEGER 2))))
    (EXPORT 'SQL_MAX_NUMERIC_LEN)
    (DEFCONSTANT SQL_MAX_NUMERIC_LEN 16)
    (EXPORT '(SQL_NUMERIC_STRUCT))
    (C-TYPES:DEFCSTRUCT
        SQL_NUMERIC_STRUCT
        ((PRECISION SQLCHAR)
            (SCALE SQLSCHAR)
            (SIGN SQLCHAR)
            (VAL (SQLCHAR SQL_MAX_NUMERIC_LEN))))
    (EXPORT 'BOOKMARK)
    (C-TYPES:DEFCTYPE BOOKMARK :UNSIGNED-LONG)
    (EXPORT 'SQLWCHAR)
    (C-TYPES:DEFCTYPE SQLWCHAR :SHORT)
    (EXPORT 'SQLTCHAR)
    (C-TYPES:DEFCTYPE SQLTCHAR SQLCHAR))
(PROGN
    (EXPORT 'SQL_NULL_DATA)
    (DEFCONSTANT SQL_NULL_DATA (- 1))
    (EXPORT 'SQL_DATA_AT_EXEC)
    (DEFCONSTANT SQL_DATA_AT_EXEC (- 2))
    (EXPORT 'SQL_SUCCESS)
    (DEFCONSTANT SQL_SUCCESS 0)
    (EXPORT 'SQL_SUCCESS_WITH_INFO)
    (DEFCONSTANT SQL_SUCCESS_WITH_INFO 1)
    (EXPORT 'SQL_NO_DATA)
    (DEFCONSTANT SQL_NO_DATA 100)
    (EXPORT 'SQL_ERROR)
    (DEFCONSTANT SQL_ERROR (- 1))
    (EXPORT 'SQL_INVALID_HANDLE)
    (DEFCONSTANT SQL_INVALID_HANDLE (- 2))
    (EXPORT 'SQL_STILL_EXECUTING)
    (DEFCONSTANT SQL_STILL_EXECUTING 2)
    (EXPORT 'SQL_NEED_DATA)
    (DEFCONSTANT SQL_NEED_DATA 99)
    (PROGN (EXPORT 'SQL_SUCCEEDED) (DEFUN SQL_SUCCEEDED (RC)
        (ZEROP (LOGANDC2 RC 1))))
    (EXPORT 'SQL_NTS)
    (DEFCONSTANT SQL_NTS (- 3))
    (EXPORT 'SQL_NTSL)
    (DEFCONSTANT SQL_NTSL (- 3))
    (EXPORT 'SQL_MAX_MESSAGE_LENGTH)
    (DEFCONSTANT SQL_MAX_MESSAGE_LENGTH 512)
    (EXPORT 'SQL_DATE_LEN)
    (DEFCONSTANT SQL_DATE_LEN 10)
    (EXPORT 'SQL_TIME_LEN)
    (DEFCONSTANT SQL_TIME_LEN 8)
    (EXPORT 'SQL_TIMESTAMP_LEN)
    (DEFCONSTANT SQL_TIMESTAMP_LEN 19)
    (EXPORT 'SQL_HANDLE_ENV)
    (DEFCONSTANT SQL_HANDLE_ENV 1)
    (EXPORT 'SQL_HANDLE_DBC)
    (DEFCONSTANT SQL_HANDLE_DBC 2)
    (EXPORT 'SQL_HANDLE_STMT)
    (DEFCONSTANT SQL_HANDLE_STMT 3)
    (EXPORT 'SQL_HANDLE_DESC)
    (DEFCONSTANT SQL_HANDLE_DESC 4)
    (EXPORT 'SQL_ATTR_OUTPUT_NTS)
    (DEFCONSTANT SQL_ATTR_OUTPUT_NTS 10001)
    (EXPORT 'SQL_ATTR_AUTO_IPD)
    (DEFCONSTANT SQL_ATTR_AUTO_IPD 10001)
    (EXPORT 'SQL_ATTR_METADATA_ID)
    (DEFCONSTANT SQL_ATTR_METADATA_ID 10014)
    (EXPORT 'SQL_ATTR_APP_ROW_DESC)
    (DEFCONSTANT SQL_ATTR_APP_ROW_DESC 10010)
    (EXPORT 'SQL_ATTR_APP_PARAM_DESC)
    (DEFCONSTANT SQL_ATTR_APP_PARAM_DESC 10011)
    (EXPORT 'SQL_ATTR_IMP_ROW_DESC)
    (DEFCONSTANT SQL_ATTR_IMP_ROW_DESC 10012)
    (EXPORT 'SQL_ATTR_IMP_PARAM_DESC)
    (DEFCONSTANT SQL_ATTR_IMP_PARAM_DESC 10013)
    (EXPORT 'SQL_ATTR_CURSOR_SCROLLABLE)
    (DEFCONSTANT SQL_ATTR_CURSOR_SCROLLABLE (- 1))
    (EXPORT 'SQL_ATTR_CURSOR_SENSITIVITY)
    (DEFCONSTANT SQL_ATTR_CURSOR_SENSITIVITY (- 2))
    (EXPORT 'SQL_NONSCROLLABLE)
    (DEFCONSTANT SQL_NONSCROLLABLE 0)
    (EXPORT 'SQL_SCROLLABLE)
    (DEFCONSTANT SQL_SCROLLABLE 1)
    (EXPORT 'SQL_DESC_COUNT)
    (DEFCONSTANT SQL_DESC_COUNT 1001)
    (EXPORT 'SQL_DESC_TYPE)
    (DEFCONSTANT SQL_DESC_TYPE 1002)
    (EXPORT 'SQL_DESC_LENGTH)
    (DEFCONSTANT SQL_DESC_LENGTH 1003)
    (EXPORT 'SQL_DESC_OCTET_LENGTH_PTR)
    (DEFCONSTANT SQL_DESC_OCTET_LENGTH_PTR 1004)
    (EXPORT 'SQL_DESC_PRECISION)
    (DEFCONSTANT SQL_DESC_PRECISION 1005)
    (EXPORT 'SQL_DESC_SCALE)
    (DEFCONSTANT SQL_DESC_SCALE 1006)
    (EXPORT 'SQL_DESC_DATETIME_INTERVAL_CODE)
    (DEFCONSTANT SQL_DESC_DATETIME_INTERVAL_CODE 1007)
    (EXPORT 'SQL_DESC_NULLABLE)
    (DEFCONSTANT SQL_DESC_NULLABLE 1008)
    (EXPORT 'SQL_DESC_INDICATOR_PTR)
    (DEFCONSTANT SQL_DESC_INDICATOR_PTR 1009)
    (EXPORT 'SQL_DESC_DATA_PTR)
    (DEFCONSTANT SQL_DESC_DATA_PTR 1010)
    (EXPORT 'SQL_DESC_NAME)
    (DEFCONSTANT SQL_DESC_NAME 1011)
    (EXPORT 'SQL_DESC_UNNAMED)
    (DEFCONSTANT SQL_DESC_UNNAMED 1012)
    (EXPORT 'SQL_DESC_OCTET_LENGTH)
    (DEFCONSTANT SQL_DESC_OCTET_LENGTH 1013)
    (EXPORT 'SQL_DESC_ALLOC_TYPE)
    (DEFCONSTANT SQL_DESC_ALLOC_TYPE 1099)
    (EXPORT 'SQL_DIAG_RETURNCODE)
    (DEFCONSTANT SQL_DIAG_RETURNCODE 1)
    (EXPORT 'SQL_DIAG_NUMBER)
    (DEFCONSTANT SQL_DIAG_NUMBER 2)
    (EXPORT 'SQL_DIAG_ROW_COUNT)
    (DEFCONSTANT SQL_DIAG_ROW_COUNT 3)
    (EXPORT 'SQL_DIAG_SQLSTATE)
    (DEFCONSTANT SQL_DIAG_SQLSTATE 4)
    (EXPORT 'SQL_DIAG_NATIVE)
    (DEFCONSTANT SQL_DIAG_NATIVE 5)
    (EXPORT 'SQL_DIAG_MESSAGE_TEXT)
    (DEFCONSTANT SQL_DIAG_MESSAGE_TEXT 6)
    (EXPORT 'SQL_DIAG_DYNAMIC_FUNCTION)
    (DEFCONSTANT SQL_DIAG_DYNAMIC_FUNCTION 7)
    (EXPORT 'SQL_DIAG_CLASS_ORIGIN)
    (DEFCONSTANT SQL_DIAG_CLASS_ORIGIN 8)
    (EXPORT 'SQL_DIAG_SUBCLASS_ORIGIN)
    (DEFCONSTANT SQL_DIAG_SUBCLASS_ORIGIN 9)
    (EXPORT 'SQL_DIAG_CONNECTION_NAME)
    (DEFCONSTANT SQL_DIAG_CONNECTION_NAME 10)
    (EXPORT 'SQL_DIAG_SERVER_NAME)
    (DEFCONSTANT SQL_DIAG_SERVER_NAME 11)
    (EXPORT 'SQL_DIAG_DYNAMIC_FUNCTION_CODE)
    (DEFCONSTANT SQL_DIAG_DYNAMIC_FUNCTION_CODE 12)
    (EXPORT 'SQL_DIAG_ALTER_TABLE)
    (DEFCONSTANT SQL_DIAG_ALTER_TABLE 4)
    (EXPORT 'SQL_DIAG_CREATE_INDEX)
    (DEFCONSTANT SQL_DIAG_CREATE_INDEX (- 1))
    (EXPORT 'SQL_DIAG_CREATE_TABLE)
    (DEFCONSTANT SQL_DIAG_CREATE_TABLE 77)
    (EXPORT 'SQL_DIAG_CREATE_VIEW)
    (DEFCONSTANT SQL_DIAG_CREATE_VIEW 84)
    (EXPORT 'SQL_DIAG_DELETE_WHERE)
    (DEFCONSTANT SQL_DIAG_DELETE_WHERE 19)
    (EXPORT 'SQL_DIAG_DROP_INDEX)
    (DEFCONSTANT SQL_DIAG_DROP_INDEX (- 2))
    (EXPORT 'SQL_DIAG_DROP_TABLE)
    (DEFCONSTANT SQL_DIAG_DROP_TABLE 32)
    (EXPORT 'SQL_DIAG_DROP_VIEW)
    (DEFCONSTANT SQL_DIAG_DROP_VIEW 36)
    (EXPORT 'SQL_DIAG_DYNAMIC_DELETE_CURSOR)
    (DEFCONSTANT SQL_DIAG_DYNAMIC_DELETE_CURSOR 38)
    (EXPORT 'SQL_DIAG_DYNAMIC_UPDATE_CURSOR)
    (DEFCONSTANT SQL_DIAG_DYNAMIC_UPDATE_CURSOR 81)
    (EXPORT 'SQL_DIAG_GRANT)
    (DEFCONSTANT SQL_DIAG_GRANT 48)
    (EXPORT 'SQL_DIAG_INSERT)
    (DEFCONSTANT SQL_DIAG_INSERT 50)
    (EXPORT 'SQL_DIAG_REVOKE)
    (DEFCONSTANT SQL_DIAG_REVOKE 59)
    (EXPORT 'SQL_DIAG_SELECT_CURSOR)
    (DEFCONSTANT SQL_DIAG_SELECT_CURSOR 85)
    (EXPORT 'SQL_DIAG_UNKNOWN_STATEMENT)
    (DEFCONSTANT SQL_DIAG_UNKNOWN_STATEMENT 0)
    (EXPORT 'SQL_DIAG_UPDATE_WHERE)
    (DEFCONSTANT SQL_DIAG_UPDATE_WHERE 82)
    (EXPORT 'SQL_UNKNOWN_TYPE)
    (DEFCONSTANT SQL_UNKNOWN_TYPE 0)
    (EXPORT 'SQL_CHAR)
    (DEFCONSTANT SQL_CHAR 1)
    (EXPORT 'SQL_NUMERIC)
    (DEFCONSTANT SQL_NUMERIC 2)
    (EXPORT 'SQL_DECIMAL)
    (DEFCONSTANT SQL_DECIMAL 3)
    (EXPORT 'SQL_INTEGER)
    (DEFCONSTANT SQL_INTEGER 4)
    (EXPORT 'SQL_SMALLINT)
    (DEFCONSTANT SQL_SMALLINT 5)
    (EXPORT 'SQL_FLOAT)
    (DEFCONSTANT SQL_FLOAT 6)
    (EXPORT 'SQL_REAL)
    (DEFCONSTANT SQL_REAL 7)
    (EXPORT 'SQL_DOUBLE)
    (DEFCONSTANT SQL_DOUBLE 8)
    (EXPORT 'SQL_DATETIME)
    (DEFCONSTANT SQL_DATETIME 9)
    (EXPORT 'SQL_VARCHAR)
    (DEFCONSTANT SQL_VARCHAR 12)
    (EXPORT 'SQL_TYPE_DATE)
    (DEFCONSTANT SQL_TYPE_DATE 91)
    (EXPORT 'SQL_TYPE_TIME)
    (DEFCONSTANT SQL_TYPE_TIME 92)
    (EXPORT 'SQL_TYPE_TIMESTAMP)
    (DEFCONSTANT SQL_TYPE_TIMESTAMP 93)
    (EXPORT 'SQL_UNSPECIFIED)
    (DEFCONSTANT SQL_UNSPECIFIED 0)
    (EXPORT 'SQL_INSENSITIVE)
    (DEFCONSTANT SQL_INSENSITIVE 1)
    (EXPORT 'SQL_SENSITIVE)
    (DEFCONSTANT SQL_SENSITIVE 2)
    (EXPORT 'SQL_ALL_TYPES)
    (DEFCONSTANT SQL_ALL_TYPES 0)
    (EXPORT 'SQL_DEFAULT)
    (DEFCONSTANT SQL_DEFAULT 99)
    (EXPORT 'SQL_ARD_TYPE)
    (DEFCONSTANT SQL_ARD_TYPE (- 99))
    (EXPORT 'SQL_CODE_DATE)
    (DEFCONSTANT SQL_CODE_DATE 1)
    (EXPORT 'SQL_CODE_TIME)
    (DEFCONSTANT SQL_CODE_TIME 2)
    (EXPORT 'SQL_CODE_TIMESTAMP)
    (DEFCONSTANT SQL_CODE_TIMESTAMP 3)
    (EXPORT 'SQL_FALSE)
    (DEFCONSTANT SQL_FALSE 0)
    (EXPORT 'SQL_TRUE)
    (DEFCONSTANT SQL_TRUE 1)
    (EXPORT 'SQL_NO_NULLS)
    (DEFCONSTANT SQL_NO_NULLS 0)
    (EXPORT 'SQL_NULLABLE)
    (DEFCONSTANT SQL_NULLABLE 1)
    (EXPORT 'SQL_NULLABLE_UNKNOWN)
    (DEFCONSTANT SQL_NULLABLE_UNKNOWN 2)
    (EXPORT 'SQL_PRED_NONE)
    (DEFCONSTANT SQL_PRED_NONE 0)
    (EXPORT 'SQL_PRED_CHAR)
    (DEFCONSTANT SQL_PRED_CHAR 1)
    (EXPORT 'SQL_PRED_BASIC)
    (DEFCONSTANT SQL_PRED_BASIC 2)
    (EXPORT 'SQL_NAMED)
    (DEFCONSTANT SQL_NAMED 0)
    (EXPORT 'SQL_UNNAMED)
    (DEFCONSTANT SQL_UNNAMED 1)
    (EXPORT 'SQL_DESC_ALLOC_AUTO)
    (DEFCONSTANT SQL_DESC_ALLOC_AUTO 1)
    (EXPORT 'SQL_DESC_ALLOC_USER)
    (DEFCONSTANT SQL_DESC_ALLOC_USER 2)
    (EXPORT 'SQL_CLOSE)
    (DEFCONSTANT SQL_CLOSE 0)
    (EXPORT 'SQL_DROP)
    (DEFCONSTANT SQL_DROP 1)
    (EXPORT 'SQL_UNBIND)
    (DEFCONSTANT SQL_UNBIND 2)
    (EXPORT 'SQL_RESET_PARAMS)
    (DEFCONSTANT SQL_RESET_PARAMS 3)
    (EXPORT 'SQL_FETCH_NEXT)
    (DEFCONSTANT SQL_FETCH_NEXT 1)
    (EXPORT 'SQL_FETCH_FIRST)
    (DEFCONSTANT SQL_FETCH_FIRST 2)
    (EXPORT 'SQL_FETCH_LAST)
    (DEFCONSTANT SQL_FETCH_LAST 3)
    (EXPORT 'SQL_FETCH_PRIOR)
    (DEFCONSTANT SQL_FETCH_PRIOR 4)
    (EXPORT 'SQL_FETCH_ABSOLUTE)
    (DEFCONSTANT SQL_FETCH_ABSOLUTE 5)
    (EXPORT 'SQL_FETCH_RELATIVE)
    (DEFCONSTANT SQL_FETCH_RELATIVE 6)
    (EXPORT 'SQL_COMMIT)
    (DEFCONSTANT SQL_COMMIT 0)
    (EXPORT 'SQL_ROLLBACK)
    (DEFCONSTANT SQL_ROLLBACK 1)
    (EXPORT 'SQL_NULL_HENV)
    (DEFCONSTANT SQL_NULL_HENV 0)
    (EXPORT 'SQL_NULL_HDBC)
    (DEFCONSTANT SQL_NULL_HDBC 0)
    (EXPORT 'SQL_NULL_HSTMT)
    (DEFCONSTANT SQL_NULL_HSTMT 0)
    (EXPORT 'SQL_NULL_HDESC)
    (DEFCONSTANT SQL_NULL_HDESC 0)
    (EXPORT 'SQL_NULL_HANDLE)
    (DEFCONSTANT SQL_NULL_HANDLE 0)
    (EXPORT 'SQL_SCOPE_CURROW)
    (DEFCONSTANT SQL_SCOPE_CURROW 0)
    (EXPORT 'SQL_SCOPE_TRANSACTION)
    (DEFCONSTANT SQL_SCOPE_TRANSACTION 1)
    (EXPORT 'SQL_SCOPE_SESSION)
    (DEFCONSTANT SQL_SCOPE_SESSION 2)
    (EXPORT 'SQL_PC_UNKNOWN)
    (DEFCONSTANT SQL_PC_UNKNOWN 0)
    (EXPORT 'SQL_PC_NON_PSEUDO)
    (DEFCONSTANT SQL_PC_NON_PSEUDO 1)
    (EXPORT 'SQL_PC_PSEUDO)
    (DEFCONSTANT SQL_PC_PSEUDO 2)
    (EXPORT 'SQL_ROW_IDENTIFIER)
    (DEFCONSTANT SQL_ROW_IDENTIFIER 1)
    (EXPORT 'SQL_INDEX_UNIQUE)
    (DEFCONSTANT SQL_INDEX_UNIQUE 0)
    (EXPORT 'SQL_INDEX_ALL)
    (DEFCONSTANT SQL_INDEX_ALL 1)
    (EXPORT 'SQL_INDEX_CLUSTERED)
    (DEFCONSTANT SQL_INDEX_CLUSTERED 1)
    (EXPORT 'SQL_INDEX_HASHED)
    (DEFCONSTANT SQL_INDEX_HASHED 2)
    (EXPORT 'SQL_INDEX_OTHER)
    (DEFCONSTANT SQL_INDEX_OTHER 3)
    (EXPORT 'SQL_API_SQLALLOCCONNECT)
    (DEFCONSTANT SQL_API_SQLALLOCCONNECT 1)
    (EXPORT 'SQL_API_SQLALLOCENV)
    (DEFCONSTANT SQL_API_SQLALLOCENV 2)
    (EXPORT 'SQL_API_SQLALLOCHANDLE)
    (DEFCONSTANT SQL_API_SQLALLOCHANDLE 1001)
    (EXPORT 'SQL_API_SQLALLOCSTMT)
    (DEFCONSTANT SQL_API_SQLALLOCSTMT 3)
    (EXPORT 'SQL_API_SQLBINDCOL)
    (DEFCONSTANT SQL_API_SQLBINDCOL 4)
    (EXPORT 'SQL_API_SQLBINDPARAM)
    (DEFCONSTANT SQL_API_SQLBINDPARAM 1002)
    (EXPORT 'SQL_API_SQLCANCEL)
    (DEFCONSTANT SQL_API_SQLCANCEL 5)
    (EXPORT 'SQL_API_SQLCLOSECURSOR)
    (DEFCONSTANT SQL_API_SQLCLOSECURSOR 1003)
    (EXPORT 'SQL_API_SQLCOLATTRIBUTE)
    (DEFCONSTANT SQL_API_SQLCOLATTRIBUTE 6)
    (EXPORT 'SQL_API_SQLCOLUMNS)
    (DEFCONSTANT SQL_API_SQLCOLUMNS 40)
    (EXPORT 'SQL_API_SQLCONNECT)
    (DEFCONSTANT SQL_API_SQLCONNECT 7)
    (EXPORT 'SQL_API_SQLCOPYDESC)
    (DEFCONSTANT SQL_API_SQLCOPYDESC 1004)
    (EXPORT 'SQL_API_SQLDATASOURCES)
    (DEFCONSTANT SQL_API_SQLDATASOURCES 57)
    (EXPORT 'SQL_API_SQLDESCRIBECOL)
    (DEFCONSTANT SQL_API_SQLDESCRIBECOL 8)
    (EXPORT 'SQL_API_SQLDISCONNECT)
    (DEFCONSTANT SQL_API_SQLDISCONNECT 9)
    (EXPORT 'SQL_API_SQLENDTRAN)
    (DEFCONSTANT SQL_API_SQLENDTRAN 1005)
    (EXPORT 'SQL_API_SQLERROR)
    (DEFCONSTANT SQL_API_SQLERROR 10)
    (EXPORT 'SQL_API_SQLEXECDIRECT)
    (DEFCONSTANT SQL_API_SQLEXECDIRECT 11)
    (EXPORT 'SQL_API_SQLEXECUTE)
    (DEFCONSTANT SQL_API_SQLEXECUTE 12)
    (EXPORT 'SQL_API_SQLFETCH)
    (DEFCONSTANT SQL_API_SQLFETCH 13)
    (EXPORT 'SQL_API_SQLFETCHSCROLL)
    (DEFCONSTANT SQL_API_SQLFETCHSCROLL 1021)
    (EXPORT 'SQL_API_SQLFREECONNECT)
    (DEFCONSTANT SQL_API_SQLFREECONNECT 14)
    (EXPORT 'SQL_API_SQLFREEENV)
    (DEFCONSTANT SQL_API_SQLFREEENV 15)
    (EXPORT 'SQL_API_SQLFREEHANDLE)
    (DEFCONSTANT SQL_API_SQLFREEHANDLE 1006)
    (EXPORT 'SQL_API_SQLFREESTMT)
    (DEFCONSTANT SQL_API_SQLFREESTMT 16)
    (EXPORT 'SQL_API_SQLGETCONNECTATTR)
    (DEFCONSTANT SQL_API_SQLGETCONNECTATTR 1007)
    (EXPORT 'SQL_API_SQLGETCONNECTOPTION)
    (DEFCONSTANT SQL_API_SQLGETCONNECTOPTION 42)
    (EXPORT 'SQL_API_SQLGETCURSORNAME)
    (DEFCONSTANT SQL_API_SQLGETCURSORNAME 17)
    (EXPORT 'SQL_API_SQLGETDATA)
    (DEFCONSTANT SQL_API_SQLGETDATA 43)
    (EXPORT 'SQL_API_SQLGETDESCFIELD)
    (DEFCONSTANT SQL_API_SQLGETDESCFIELD 1008)
    (EXPORT 'SQL_API_SQLGETDESCREC)
    (DEFCONSTANT SQL_API_SQLGETDESCREC 1009)
    (EXPORT 'SQL_API_SQLGETDIAGFIELD)
    (DEFCONSTANT SQL_API_SQLGETDIAGFIELD 1010)
    (EXPORT 'SQL_API_SQLGETDIAGREC)
    (DEFCONSTANT SQL_API_SQLGETDIAGREC 1011)
    (EXPORT 'SQL_API_SQLGETENVATTR)
    (DEFCONSTANT SQL_API_SQLGETENVATTR 1012)
    (EXPORT 'SQL_API_SQLGETFUNCTIONS)
    (DEFCONSTANT SQL_API_SQLGETFUNCTIONS 44)
    (EXPORT 'SQL_API_SQLGETINFO)
    (DEFCONSTANT SQL_API_SQLGETINFO 45)
    (EXPORT 'SQL_API_SQLGETSTMTATTR)
    (DEFCONSTANT SQL_API_SQLGETSTMTATTR 1014)
    (EXPORT 'SQL_API_SQLGETSTMTOPTION)
    (DEFCONSTANT SQL_API_SQLGETSTMTOPTION 46)
    (EXPORT 'SQL_API_SQLGETTYPEINFO)
    (DEFCONSTANT SQL_API_SQLGETTYPEINFO 47)
    (EXPORT 'SQL_API_SQLNUMRESULTCOLS)
    (DEFCONSTANT SQL_API_SQLNUMRESULTCOLS 18)
    (EXPORT 'SQL_API_SQLPARAMDATA)
    (DEFCONSTANT SQL_API_SQLPARAMDATA 48)
    (EXPORT 'SQL_API_SQLPREPARE)
    (DEFCONSTANT SQL_API_SQLPREPARE 19)
    (EXPORT 'SQL_API_SQLPUTDATA)
    (DEFCONSTANT SQL_API_SQLPUTDATA 49)
    (EXPORT 'SQL_API_SQLROWCOUNT)
    (DEFCONSTANT SQL_API_SQLROWCOUNT 20)
    (EXPORT 'SQL_API_SQLSETCONNECTATTR)
    (DEFCONSTANT SQL_API_SQLSETCONNECTATTR 1016)
    (EXPORT 'SQL_API_SQLSETCONNECTOPTION)
    (DEFCONSTANT SQL_API_SQLSETCONNECTOPTION 50)
    (EXPORT 'SQL_API_SQLSETCURSORNAME)
    (DEFCONSTANT SQL_API_SQLSETCURSORNAME 21)
    (EXPORT 'SQL_API_SQLSETDESCFIELD)
    (DEFCONSTANT SQL_API_SQLSETDESCFIELD 1017)
    (EXPORT 'SQL_API_SQLSETDESCREC)
    (DEFCONSTANT SQL_API_SQLSETDESCREC 1018)
    (EXPORT 'SQL_API_SQLSETENVATTR)
    (DEFCONSTANT SQL_API_SQLSETENVATTR 1019)
    (EXPORT 'SQL_API_SQLSETPARAM)
    (DEFCONSTANT SQL_API_SQLSETPARAM 22)
    (EXPORT 'SQL_API_SQLSETSTMTATTR)
    (DEFCONSTANT SQL_API_SQLSETSTMTATTR 1020)
    (EXPORT 'SQL_API_SQLSETSTMTOPTION)
    (DEFCONSTANT SQL_API_SQLSETSTMTOPTION 51)
    (EXPORT 'SQL_API_SQLSPECIALCOLUMNS)
    (DEFCONSTANT SQL_API_SQLSPECIALCOLUMNS 52)
    (EXPORT 'SQL_API_SQLSTATISTICS)
    (DEFCONSTANT SQL_API_SQLSTATISTICS 53)
    (EXPORT 'SQL_API_SQLTABLES)
    (DEFCONSTANT SQL_API_SQLTABLES 54)
    (EXPORT 'SQL_API_SQLTRANSACT)
    (DEFCONSTANT SQL_API_SQLTRANSACT 23)
    (EXPORT 'SQL_MAX_DRIVER_CONNECTIONS)
    (DEFCONSTANT SQL_MAX_DRIVER_CONNECTIONS 0)
    (EXPORT 'SQL_MAXIMUM_DRIVER_CONNECTIONS)
    (DEFCONSTANT SQL_MAXIMUM_DRIVER_CONNECTIONS SQL_MAX_DRIVER_CONNECTIONS)
    (EXPORT 'SQL_MAX_CONCURRENT_ACTIVITIES)
    (DEFCONSTANT SQL_MAX_CONCURRENT_ACTIVITIES 1)
    (EXPORT 'SQL_MAXIMUM_CONCURRENT_ACTIVITIES)
    (DEFCONSTANT SQL_MAXIMUM_CONCURRENT_ACTIVITIES SQL_MAX_CONCURRENT_ACTIVITIES)
    (EXPORT 'SQL_DATA_SOURCE_NAME)
    (DEFCONSTANT SQL_DATA_SOURCE_NAME 2)
    (EXPORT 'SQL_FETCH_DIRECTION)
    (DEFCONSTANT SQL_FETCH_DIRECTION 8)
    (EXPORT 'SQL_SERVER_NAME)
    (DEFCONSTANT SQL_SERVER_NAME 13)
    (EXPORT 'SQL_SEARCH_PATTERN_ESCAPE)
    (DEFCONSTANT SQL_SEARCH_PATTERN_ESCAPE 14)
    (EXPORT 'SQL_DBMS_NAME)
    (DEFCONSTANT SQL_DBMS_NAME 17)
    (EXPORT 'SQL_DBMS_VER)
    (DEFCONSTANT SQL_DBMS_VER 18)
    (EXPORT 'SQL_ACCESSIBLE_TABLES)
    (DEFCONSTANT SQL_ACCESSIBLE_TABLES 19)
    (EXPORT 'SQL_ACCESSIBLE_PROCEDURES)
    (DEFCONSTANT SQL_ACCESSIBLE_PROCEDURES 20)
    (EXPORT 'SQL_CURSOR_COMMIT_BEHAVIOR)
    (DEFCONSTANT SQL_CURSOR_COMMIT_BEHAVIOR 23)
    (EXPORT 'SQL_DATA_SOURCE_READ_ONLY)
    (DEFCONSTANT SQL_DATA_SOURCE_READ_ONLY 25)
    (EXPORT 'SQL_DEFAULT_TXN_ISOLATION)
    (DEFCONSTANT SQL_DEFAULT_TXN_ISOLATION 26)
    (EXPORT 'SQL_IDENTIFIER_CASE)
    (DEFCONSTANT SQL_IDENTIFIER_CASE 28)
    (EXPORT 'SQL_IDENTIFIER_QUOTE_CHAR)
    (DEFCONSTANT SQL_IDENTIFIER_QUOTE_CHAR 29)
    (EXPORT 'SQL_MAX_COLUMN_NAME_LEN)
    (DEFCONSTANT SQL_MAX_COLUMN_NAME_LEN 30)
    (EXPORT 'SQL_MAXIMUM_COLUMN_NAME_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_COLUMN_NAME_LENGTH SQL_MAX_COLUMN_NAME_LEN)
    (EXPORT 'SQL_MAX_CURSOR_NAME_LEN)
    (DEFCONSTANT SQL_MAX_CURSOR_NAME_LEN 31)
    (EXPORT 'SQL_MAXIMUM_CURSOR_NAME_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_CURSOR_NAME_LENGTH SQL_MAX_CURSOR_NAME_LEN)
    (EXPORT 'SQL_MAX_SCHEMA_NAME_LEN)
    (DEFCONSTANT SQL_MAX_SCHEMA_NAME_LEN 32)
    (EXPORT 'SQL_MAXIMUM_SCHEMA_NAME_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_SCHEMA_NAME_LENGTH SQL_MAX_SCHEMA_NAME_LEN)
    (EXPORT 'SQL_MAX_CATALOG_NAME_LEN)
    (DEFCONSTANT SQL_MAX_CATALOG_NAME_LEN 34)
    (EXPORT 'SQL_MAXIMUM_CATALOG_NAME_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_CATALOG_NAME_LENGTH SQL_MAX_CATALOG_NAME_LEN)
    (EXPORT 'SQL_MAX_TABLE_NAME_LEN)
    (DEFCONSTANT SQL_MAX_TABLE_NAME_LEN 35)
    (EXPORT 'SQL_SCROLL_CONCURRENCY)
    (DEFCONSTANT SQL_SCROLL_CONCURRENCY 43)
    (EXPORT 'SQL_TXN_CAPABLE)
    (DEFCONSTANT SQL_TXN_CAPABLE 46)
    (EXPORT 'SQL_TRANSACTION_CAPABLE)
    (DEFCONSTANT SQL_TRANSACTION_CAPABLE SQL_TXN_CAPABLE)
    (EXPORT 'SQL_USER_NAME)
    (DEFCONSTANT SQL_USER_NAME 47)
    (EXPORT 'SQL_TXN_ISOLATION_OPTION)
    (DEFCONSTANT SQL_TXN_ISOLATION_OPTION 72)
    (EXPORT 'SQL_TRANSACTION_ISOLATION_OPTION)
    (DEFCONSTANT SQL_TRANSACTION_ISOLATION_OPTION SQL_TXN_ISOLATION_OPTION)
    (EXPORT 'SQL_INTEGRITY)
    (DEFCONSTANT SQL_INTEGRITY 73)
    (EXPORT 'SQL_GETDATA_EXTENSIONS)
    (DEFCONSTANT SQL_GETDATA_EXTENSIONS 81)
    (EXPORT 'SQL_NULL_COLLATION)
    (DEFCONSTANT SQL_NULL_COLLATION 85)
    (EXPORT 'SQL_ALTER_TABLE)
    (DEFCONSTANT SQL_ALTER_TABLE 86)
    (EXPORT 'SQL_ORDER_BY_COLUMNS_IN_SELECT)
    (DEFCONSTANT SQL_ORDER_BY_COLUMNS_IN_SELECT 90)
    (EXPORT 'SQL_SPECIAL_CHARACTERS)
    (DEFCONSTANT SQL_SPECIAL_CHARACTERS 94)
    (EXPORT 'SQL_MAX_COLUMNS_IN_GROUP_BY)
    (DEFCONSTANT SQL_MAX_COLUMNS_IN_GROUP_BY 97)
    (EXPORT 'SQL_MAXIMUM_COLUMNS_IN_GROUP_BY)
    (DEFCONSTANT SQL_MAXIMUM_COLUMNS_IN_GROUP_BY SQL_MAX_COLUMNS_IN_GROUP_BY)
    (EXPORT 'SQL_MAX_COLUMNS_IN_INDEX)
    (DEFCONSTANT SQL_MAX_COLUMNS_IN_INDEX 98)
    (EXPORT 'SQL_MAXIMUM_COLUMNS_IN_INDEX)
    (DEFCONSTANT SQL_MAXIMUM_COLUMNS_IN_INDEX SQL_MAX_COLUMNS_IN_INDEX)
    (EXPORT 'SQL_MAX_COLUMNS_IN_ORDER_BY)
    (DEFCONSTANT SQL_MAX_COLUMNS_IN_ORDER_BY 99)
    (EXPORT 'SQL_MAXIMUM_COLUMNS_IN_ORDER_BY)
    (DEFCONSTANT SQL_MAXIMUM_COLUMNS_IN_ORDER_BY SQL_MAX_COLUMNS_IN_ORDER_BY)
    (EXPORT 'SQL_MAX_COLUMNS_IN_SELECT)
    (DEFCONSTANT SQL_MAX_COLUMNS_IN_SELECT 100)
    (EXPORT 'SQL_MAXIMUM_COLUMNS_IN_SELECT)
    (DEFCONSTANT SQL_MAXIMUM_COLUMNS_IN_SELECT SQL_MAX_COLUMNS_IN_SELECT)
    (EXPORT 'SQL_MAX_COLUMNS_IN_TABLE)
    (DEFCONSTANT SQL_MAX_COLUMNS_IN_TABLE 101)
    (EXPORT 'SQL_MAX_INDEX_SIZE)
    (DEFCONSTANT SQL_MAX_INDEX_SIZE 102)
    (EXPORT 'SQL_MAXIMUM_INDEX_SIZE)
    (DEFCONSTANT SQL_MAXIMUM_INDEX_SIZE SQL_MAX_INDEX_SIZE)
    (EXPORT 'SQL_MAX_ROW_SIZE)
    (DEFCONSTANT SQL_MAX_ROW_SIZE 104)
    (EXPORT 'SQL_MAXIMUM_ROW_SIZE)
    (DEFCONSTANT SQL_MAXIMUM_ROW_SIZE SQL_MAX_ROW_SIZE)
    (EXPORT 'SQL_MAX_STATEMENT_LEN)
    (DEFCONSTANT SQL_MAX_STATEMENT_LEN 105)
    (EXPORT 'SQL_MAXIMUM_STATEMENT_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_STATEMENT_LENGTH SQL_MAX_STATEMENT_LEN)
    (EXPORT 'SQL_MAX_TABLES_IN_SELECT)
    (DEFCONSTANT SQL_MAX_TABLES_IN_SELECT 106)
    (EXPORT 'SQL_MAXIMUM_TABLES_IN_SELECT)
    (DEFCONSTANT SQL_MAXIMUM_TABLES_IN_SELECT SQL_MAX_TABLES_IN_SELECT)
    (EXPORT 'SQL_MAX_USER_NAME_LEN)
    (DEFCONSTANT SQL_MAX_USER_NAME_LEN 107)
    (EXPORT 'SQL_MAXIMUM_USER_NAME_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_USER_NAME_LENGTH SQL_MAX_USER_NAME_LEN)
    (EXPORT 'SQL_OJ_CAPABILITIES)
    (DEFCONSTANT SQL_OJ_CAPABILITIES 115)
    (EXPORT 'SQL_OUTER_JOIN_CAPABILITIES)
    (DEFCONSTANT SQL_OUTER_JOIN_CAPABILITIES SQL_OJ_CAPABILITIES)
    (EXPORT 'SQL_XOPEN_CLI_YEAR)
    (DEFCONSTANT SQL_XOPEN_CLI_YEAR 10000)
    (EXPORT 'SQL_CURSOR_SENSITIVITY)
    (DEFCONSTANT SQL_CURSOR_SENSITIVITY 10001)
    (EXPORT 'SQL_DESCRIBE_PARAMETER)
    (DEFCONSTANT SQL_DESCRIBE_PARAMETER 10002)
    (EXPORT 'SQL_CATALOG_NAME)
    (DEFCONSTANT SQL_CATALOG_NAME 10003)
    (EXPORT 'SQL_COLLATION_SEQ)
    (DEFCONSTANT SQL_COLLATION_SEQ 10004)
    (EXPORT 'SQL_MAX_IDENTIFIER_LEN)
    (DEFCONSTANT SQL_MAX_IDENTIFIER_LEN 10005)
    (EXPORT 'SQL_MAXIMUM_IDENTIFIER_LENGTH)
    (DEFCONSTANT SQL_MAXIMUM_IDENTIFIER_LENGTH SQL_MAX_IDENTIFIER_LEN)
    (EXPORT 'SQL_AT_ADD_COLUMN)
    (DEFCONSTANT SQL_AT_ADD_COLUMN 1)
    (EXPORT 'SQL_AT_DROP_COLUMN)
    (DEFCONSTANT SQL_AT_DROP_COLUMN 2)
    (EXPORT 'SQL_AT_ADD_CONSTRAINT)
    (DEFCONSTANT SQL_AT_ADD_CONSTRAINT 8)
    (EXPORT 'SQL_AM_NONE)
    (DEFCONSTANT SQL_AM_NONE 0)
    (EXPORT 'SQL_AM_CONNECTION)
    (DEFCONSTANT SQL_AM_CONNECTION 1)
    (EXPORT 'SQL_AM_STATEMENT)
    (DEFCONSTANT SQL_AM_STATEMENT 2)
    (EXPORT 'SQL_CB_DELETE)
    (DEFCONSTANT SQL_CB_DELETE 0)
    (EXPORT 'SQL_CB_CLOSE)
    (DEFCONSTANT SQL_CB_CLOSE 1)
    (EXPORT 'SQL_CB_PRESERVE)
    (DEFCONSTANT SQL_CB_PRESERVE 2)
    (EXPORT 'SQL_FD_FETCH_NEXT)
    (DEFCONSTANT SQL_FD_FETCH_NEXT 1)
    (EXPORT 'SQL_FD_FETCH_FIRST)
    (DEFCONSTANT SQL_FD_FETCH_FIRST 2)
    (EXPORT 'SQL_FD_FETCH_LAST)
    (DEFCONSTANT SQL_FD_FETCH_LAST 4)
    (EXPORT 'SQL_FD_FETCH_PRIOR)
    (DEFCONSTANT SQL_FD_FETCH_PRIOR 8)
    (EXPORT 'SQL_FD_FETCH_ABSOLUTE)
    (DEFCONSTANT SQL_FD_FETCH_ABSOLUTE 16)
    (EXPORT 'SQL_FD_FETCH_RELATIVE)
    (DEFCONSTANT SQL_FD_FETCH_RELATIVE 32)
    (EXPORT 'SQL_GD_ANY_COLUMN)
    (DEFCONSTANT SQL_GD_ANY_COLUMN 1)
    (EXPORT 'SQL_GD_ANY_ORDER)
    (DEFCONSTANT SQL_GD_ANY_ORDER 2)
    (EXPORT 'SQL_IC_UPPER)
    (DEFCONSTANT SQL_IC_UPPER 1)
    (EXPORT 'SQL_IC_LOWER)
    (DEFCONSTANT SQL_IC_LOWER 2)
    (EXPORT 'SQL_IC_SENSITIVE)
    (DEFCONSTANT SQL_IC_SENSITIVE 3)
    (EXPORT 'SQL_IC_MIXED)
    (DEFCONSTANT SQL_IC_MIXED 4)
    (EXPORT 'SQL_OJ_LEFT)
    (DEFCONSTANT SQL_OJ_LEFT 1)
    (EXPORT 'SQL_OJ_RIGHT)
    (DEFCONSTANT SQL_OJ_RIGHT 2)
    (EXPORT 'SQL_OJ_FULL)
    (DEFCONSTANT SQL_OJ_FULL 4)
    (EXPORT 'SQL_OJ_NESTED)
    (DEFCONSTANT SQL_OJ_NESTED 8)
    (EXPORT 'SQL_OJ_NOT_ORDERED)
    (DEFCONSTANT SQL_OJ_NOT_ORDERED 16)
    (EXPORT 'SQL_OJ_INNER)
    (DEFCONSTANT SQL_OJ_INNER 32)
    (EXPORT 'SQL_OJ_ALL_COMPARISON_OPS)
    (DEFCONSTANT SQL_OJ_ALL_COMPARISON_OPS 64)
    (EXPORT 'SQL_SCCO_READ_ONLY)
    (DEFCONSTANT SQL_SCCO_READ_ONLY 1)
    (EXPORT 'SQL_SCCO_LOCK)
    (DEFCONSTANT SQL_SCCO_LOCK 2)
    (EXPORT 'SQL_SCCO_OPT_ROWVER)
    (DEFCONSTANT SQL_SCCO_OPT_ROWVER 4)
    (EXPORT 'SQL_SCCO_OPT_VALUES)
    (DEFCONSTANT SQL_SCCO_OPT_VALUES 8)
    (EXPORT 'SQL_TC_NONE)
    (DEFCONSTANT SQL_TC_NONE 0)
    (EXPORT 'SQL_TC_DML)
    (DEFCONSTANT SQL_TC_DML 1)
    (EXPORT 'SQL_TC_ALL)
    (DEFCONSTANT SQL_TC_ALL 2)
    (EXPORT 'SQL_TC_DDL_COMMIT)
    (DEFCONSTANT SQL_TC_DDL_COMMIT 3)
    (EXPORT 'SQL_TC_DDL_IGNORE)
    (DEFCONSTANT SQL_TC_DDL_IGNORE 4)
    (EXPORT 'SQL_TXN_READ_UNCOMMITTED)
    (DEFCONSTANT SQL_TXN_READ_UNCOMMITTED 1)
    (EXPORT 'SQL_TRANSACTION_READ_UNCOMMITTED)
    (DEFCONSTANT SQL_TRANSACTION_READ_UNCOMMITTED SQL_TXN_READ_UNCOMMITTED)
    (EXPORT 'SQL_TXN_READ_COMMITTED)
    (DEFCONSTANT SQL_TXN_READ_COMMITTED 2)
    (EXPORT 'SQL_TRANSACTION_READ_COMMITTED)
    (DEFCONSTANT SQL_TRANSACTION_READ_COMMITTED SQL_TXN_READ_COMMITTED)
    (EXPORT 'SQL_TXN_REPEATABLE_READ)
    (DEFCONSTANT SQL_TXN_REPEATABLE_READ 4)
    (EXPORT 'SQL_TRANSACTION_REPEATABLE_READ)
    (DEFCONSTANT SQL_TRANSACTION_REPEATABLE_READ SQL_TXN_REPEATABLE_READ)
    (EXPORT 'SQL_TXN_SERIALIZABLE)
    (DEFCONSTANT SQL_TXN_SERIALIZABLE 8)
    (EXPORT 'SQL_TRANSACTION_SERIALIZABLE)
    (DEFCONSTANT SQL_TRANSACTION_SERIALIZABLE SQL_TXN_SERIALIZABLE)
    (EXPORT 'SQL_NC_HIGH)
    (DEFCONSTANT SQL_NC_HIGH 0)
    (EXPORT 'SQL_NC_LOW)
    (DEFCONSTANT SQL_NC_LOW 1)
    (EXPORT 'SQLALLOCCONNECT)
    (C-TYPES:DEFUN-DLL
        SQLALLOCCONNECT
        ((ENVIRONMENTHANDLE SQLHENV)
            (CONNECTIONHANDLE (SQLHDBC *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLAllocConnect"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLALLOCENV)
    (C-TYPES:DEFUN-DLL
        SQLALLOCENV
        ((ENVIRONMENTHANDLE (SQLHENV *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLAllocEnv"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLALLOCHANDLE)
    (C-TYPES:DEFUN-DLL
        SQLALLOCHANDLE
        ((HANDLETYPE SQLSMALLINT)
            (INPUTHANDLE SQLHANDLE)
            (OUTPUTHANDLE (SQLHANDLE *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLAllocHandle"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLALLOCSTMT)
    (C-TYPES:DEFUN-DLL
        SQLALLOCSTMT
        ((CONNECTIONHANDLE SQLHDBC)
            (STATEMENTHANDLE (SQLHSTMT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLAllocStmt"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLBINDCOL)
    (C-TYPES:DEFUN-DLL
        SQLBINDCOL
        ((STATEMENTHANDLE SQLHSTMT)
            (COLUMNNUMBER SQLUSMALLINT)
            (TARGETTYPE SQLSMALLINT)
            (TARGETVALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRLEN_OR_IND (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLBindCol"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLBINDPARAM)
    (C-TYPES:DEFUN-DLL
        SQLBINDPARAM
        ((STATEMENTHANDLE SQLHSTMT)
            (PARAMETERNUMBER SQLUSMALLINT)
            (VALUETYPE SQLSMALLINT)
            (PARAMETERTYPE SQLSMALLINT)
            (LENGTHPRECISION SQLUINTEGER)
            (PARAMETERSCALE SQLSMALLINT)
            (PARAMETERVALUE SQLPOINTER)
            (STRLEN_OR_IND (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLBindParam"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCANCEL)
    (C-TYPES:DEFUN-DLL
        SQLCANCEL
        ((STATEMENTHANDLE SQLHSTMT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLCancel"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCLOSECURSOR)
    (C-TYPES:DEFUN-DLL
        SQLCLOSECURSOR
        ((STATEMENTHANDLE SQLHSTMT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLCloseCursor"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCOLATTRIBUTE)
    (C-TYPES:DEFUN-DLL
        SQLCOLATTRIBUTE
        ((STATEMENTHANDLE SQLHSTMT)
            (COLUMNNUMBER SQLUSMALLINT)
            (FIELDIDENTIFIER SQLUSMALLINT)
            (CHARACTERATTRIBUTE SQLPOINTER)
            (BUFFERLENGTH SQLSMALLINT)
            (STRINGLENGTH (SQLSMALLINT *))
            (NUMERICATTRIBUTE SQLPOINTER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLColAttribute"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCOLUMNS)
    (C-TYPES:DEFUN-DLL
        SQLCOLUMNS
        ((STATEMENTHANDLE SQLHSTMT)
            (CATALOGNAME (SQLCHAR *))
            (NAMELENGTH1 SQLSMALLINT)
            (SCHEMANAME (SQLCHAR *))
            (NAMELENGTH2 SQLSMALLINT)
            (TABLENAME (SQLCHAR *))
            (NAMELENGTH3 SQLSMALLINT)
            (COLUMNNAME (SQLCHAR *))
            (NAMELENGTH4 SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLColumns"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCONNECT)
    (C-TYPES:DEFUN-DLL
        SQLCONNECT
        ((CONNECTIONHANDLE SQLHDBC)
            (SERVERNAME (SQLCHAR *))
            (NAMELENGTH1 SQLSMALLINT)
            (USERNAME (SQLCHAR *))
            (NAMELENGTH2 SQLSMALLINT)
            (AUTHENTICATION (SQLCHAR *))
            (NAMELENGTH3 SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLConnect"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLCOPYDESC)
    (C-TYPES:DEFUN-DLL
        SQLCOPYDESC
        ((SOURCEDESCHANDLE SQLHDESC)
            (TARGETDESCHANDLE SQLHDESC))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLCopyDesc"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLDATASOURCES)
    (C-TYPES:DEFUN-DLL
        SQLDATASOURCES
        ((ENVIRONMENTHANDLE SQLHENV)
            (DIRECTION SQLUSMALLINT)
            (SERVERNAME (SQLCHAR *))
            (BUFFERLENGTH1 SQLSMALLINT)
            (NAMELENGTH1 (SQLSMALLINT *))
            (DESCRIPTION (SQLCHAR *))
            (BUFFERLENGTH2 SQLSMALLINT)
            (NAMELENGTH2 (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLDataSources"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLDESCRIBECOL)
    (C-TYPES:DEFUN-DLL
        SQLDESCRIBECOL
        ((STATEMENTHANDLE SQLHSTMT)
            (COLUMNNUMBER SQLUSMALLINT)
            (COLUMNNAME (SQLCHAR *))
            (BUFFERLENGTH SQLSMALLINT)
            (NAMELENGTH (SQLSMALLINT *))
            (DATATYPE (SQLSMALLINT *))
            (COLUMNSIZE (SQLUINTEGER *))
            (DECIMALDIGITS (SQLSMALLINT *))
            (NULLABLE (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLDescribeCol"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLDISCONNECT)
    (C-TYPES:DEFUN-DLL
        SQLDISCONNECT
        ((CONNECTIONHANDLE SQLHDBC))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLDisconnect"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLENDTRAN)
    (C-TYPES:DEFUN-DLL
        SQLENDTRAN
        ((HANDLETYPE SQLSMALLINT)
            (HANDLE SQLHANDLE)
            (COMPLETIONTYPE SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLEndTran"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLERROR)
    (C-TYPES:DEFUN-DLL
        SQLERROR
        ((ENVIRONMENTHANDLE SQLHENV)
            (CONNECTIONHANDLE SQLHDBC)
            (STATEMENTHANDLE SQLHSTMT)
            (SQLSTATE (SQLCHAR *))
            (NATIVEERROR (SQLINTEGER *))
            (MESSAGETEXT (SQLCHAR *))
            (BUFFERLENGTH SQLSMALLINT)
            (TEXTLENGTH (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLError"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLEXECDIRECT)
    (C-TYPES:DEFUN-DLL
        SQLEXECDIRECT
        ((STATEMENTHANDLE SQLHSTMT)
            (STATEMENTTEXT (SQLCHAR *))
            (TEXTLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLExecDirect"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLEXECUTE)
    (C-TYPES:DEFUN-DLL
        SQLEXECUTE
        ((STATEMENTHANDLE SQLHSTMT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLExecute"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFETCH)
    (C-TYPES:DEFUN-DLL
        SQLFETCH
        ((STATEMENTHANDLE SQLHSTMT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFetch"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFETCHSCROLL)
    (C-TYPES:DEFUN-DLL
        SQLFETCHSCROLL
        ((STATEMENTHANDLE SQLHSTMT)
            (FETCHORIENTATION SQLSMALLINT)
            (FETCHOFFSET SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFetchScroll"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFREECONNECT)
    (C-TYPES:DEFUN-DLL
        SQLFREECONNECT
        ((CONNECTIONHANDLE SQLHDBC))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFreeConnect"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFREEENV)
    (C-TYPES:DEFUN-DLL
        SQLFREEENV
        ((ENVIRONMENTHANDLE SQLHENV))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFreeEnv"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFREEHANDLE)
    (C-TYPES:DEFUN-DLL
        SQLFREEHANDLE
        ((HANDLETYPE SQLSMALLINT)
            (HANDLE SQLHANDLE))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFreeHandle"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLFREESTMT)
    (C-TYPES:DEFUN-DLL
        SQLFREESTMT
        ((STATEMENTHANDLE SQLHSTMT)
            (OPTION SQLUSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLFreeStmt"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETCONNECTATTR)
    (C-TYPES:DEFUN-DLL
        SQLGETCONNECTATTR
        ((CONNECTIONHANDLE SQLHDBC)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRINGLENGTH (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetConnectAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETCONNECTOPTION)
    (C-TYPES:DEFUN-DLL
        SQLGETCONNECTOPTION
        ((CONNECTIONHANDLE SQLHDBC)
            (OPTION SQLUSMALLINT)
            (VALUE SQLPOINTER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetConnectOption"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETCURSORNAME)
    (C-TYPES:DEFUN-DLL
        SQLGETCURSORNAME
        ((STATEMENTHANDLE SQLHSTMT)
            (CURSORNAME (SQLCHAR *))
            (BUFFERLENGTH SQLSMALLINT)
            (NAMELENGTH (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetCursorName"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETDATA)
    (C-TYPES:DEFUN-DLL
        SQLGETDATA
        ((STATEMENTHANDLE SQLHSTMT)
            (COLUMNNUMBER SQLUSMALLINT)
            (TARGETTYPE SQLSMALLINT)
            (TARGETVALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRLEN_OR_IND (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetData"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETDESCFIELD)
    (C-TYPES:DEFUN-DLL
        SQLGETDESCFIELD
        ((DESCRIPTORHANDLE SQLHDESC)
            (RECNUMBER SQLSMALLINT)
            (FIELDIDENTIFIER SQLSMALLINT)
            (VALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRINGLENGTH (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetDescField"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETDESCREC)
    (C-TYPES:DEFUN-DLL
        SQLGETDESCREC
        ((DESCRIPTORHANDLE SQLHDESC)
            (RECNUMBER SQLSMALLINT)
            (NAME (SQLCHAR *))
            (BUFFERLENGTH SQLSMALLINT)
            (STRINGLENGTH (SQLSMALLINT *))
            (TYPE (SQLSMALLINT *))
            (SUBTYPE (SQLSMALLINT *))
            (LENGTH (SQLINTEGER *))
            (PRECISION (SQLSMALLINT *))
            (SCALE (SQLSMALLINT *))
            (NULLABLE (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetDescRec"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETDIAGFIELD)
    (C-TYPES:DEFUN-DLL
        SQLGETDIAGFIELD
        ((HANDLETYPE SQLSMALLINT)
            (HANDLE SQLHANDLE)
            (RECNUMBER SQLSMALLINT)
            (DIAGIDENTIFIER SQLSMALLINT)
            (DIAGINFO SQLPOINTER)
            (BUFFERLENGTH SQLSMALLINT)
            (STRINGLENGTH (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetDiagField"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETDIAGREC)
    (C-TYPES:DEFUN-DLL
        SQLGETDIAGREC
        ((HANDLETYPE SQLSMALLINT)
            (HANDLE SQLHANDLE)
            (RECNUMBER SQLSMALLINT)
            (SQLSTATE (SQLCHAR *))
            (NATIVEERROR (SQLINTEGER *))
            (MESSAGETEXT (SQLCHAR *))
            (BUFFERLENGTH SQLSMALLINT)
            (TEXTLENGTH (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetDiagRec"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETENVATTR)
    (C-TYPES:DEFUN-DLL
        SQLGETENVATTR
        ((ENVIRONMENTHANDLE SQLHENV)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRINGLENGTH (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetEnvAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETFUNCTIONS)
    (C-TYPES:DEFUN-DLL
        SQLGETFUNCTIONS
        ((CONNECTIONHANDLE SQLHDBC)
            (FUNCTIONID SQLUSMALLINT)
            (SUPPORTED (SQLUSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetFunctions"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETINFO)
    (C-TYPES:DEFUN-DLL
        SQLGETINFO
        ((CONNECTIONHANDLE SQLHDBC)
            (INFOTYPE SQLUSMALLINT)
            (INFOVALUE SQLPOINTER)
            (BUFFERLENGTH SQLSMALLINT)
            (STRINGLENGTH (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetInfo"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETSTMTATTR)
    (C-TYPES:DEFUN-DLL
        SQLGETSTMTATTR
        ((STATEMENTHANDLE SQLHSTMT)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER)
            (STRINGLENGTH (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetStmtAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETSTMTOPTION)
    (C-TYPES:DEFUN-DLL
        SQLGETSTMTOPTION
        ((STATEMENTHANDLE SQLHSTMT)
            (OPTION SQLUSMALLINT)
            (VALUE SQLPOINTER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetStmtOption"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLGETTYPEINFO)
    (C-TYPES:DEFUN-DLL
        SQLGETTYPEINFO
        ((STATEMENTHANDLE SQLHSTMT)
            (DATATYPE SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLGetTypeInfo"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLNUMRESULTCOLS)
    (C-TYPES:DEFUN-DLL
        SQLNUMRESULTCOLS
        ((STATEMENTHANDLE SQLHSTMT)
            (COLUMNCOUNT (SQLSMALLINT *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLNumResultCols"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLPARAMDATA)
    (C-TYPES:DEFUN-DLL
        SQLPARAMDATA
        ((STATEMENTHANDLE SQLHSTMT)
            (VALUE (SQLPOINTER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLParamData"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLPREPARE)
    (C-TYPES:DEFUN-DLL
        SQLPREPARE
        ((STATEMENTHANDLE SQLHSTMT)
            (STATEMENTTEXT (SQLCHAR *))
            (TEXTLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLPrepare"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLPUTDATA)
    (C-TYPES:DEFUN-DLL
        SQLPUTDATA
        ((STATEMENTHANDLE SQLHSTMT)
            (DATA SQLPOINTER)
            (STRLEN_OR_IND SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLPutData"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLROWCOUNT)
    (C-TYPES:DEFUN-DLL
        SQLROWCOUNT
        ((STATEMENTHANDLE SQLHSTMT)
            (ROWCOUNT (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLRowCount"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETCONNECTATTR)
    (C-TYPES:DEFUN-DLL
        SQLSETCONNECTATTR
        ((CONNECTIONHANDLE SQLHDBC)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (STRINGLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetConnectAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETCONNECTOPTION)
    (C-TYPES:DEFUN-DLL
        SQLSETCONNECTOPTION
        ((CONNECTIONHANDLE SQLHDBC)
            (OPTION SQLUSMALLINT)
            (VALUE SQLUINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetConnectOption"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETCURSORNAME)
    (C-TYPES:DEFUN-DLL
        SQLSETCURSORNAME
        ((STATEMENTHANDLE SQLHSTMT)
            (CURSORNAME (SQLCHAR *))
            (NAMELENGTH SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetCursorName"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETDESCFIELD)
    (C-TYPES:DEFUN-DLL
        SQLSETDESCFIELD
        ((DESCRIPTORHANDLE SQLHDESC)
            (RECNUMBER SQLSMALLINT)
            (FIELDIDENTIFIER SQLSMALLINT)
            (VALUE SQLPOINTER)
            (BUFFERLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetDescField"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETDESCREC)
    (C-TYPES:DEFUN-DLL
        SQLSETDESCREC
        ((DESCRIPTORHANDLE SQLHDESC)
            (RECNUMBER SQLSMALLINT)
            (TYPE SQLSMALLINT)
            (SUBTYPE SQLSMALLINT)
            (LENGTH SQLINTEGER)
            (PRECISION SQLSMALLINT)
            (SCALE SQLSMALLINT)
            (DATA SQLPOINTER)
            (STRINGLENGTH (SQLINTEGER *))
            (INDICATOR (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetDescRec"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETENVATTR)
    (C-TYPES:DEFUN-DLL
        SQLSETENVATTR
        ((ENVIRONMENTHANDLE SQLHENV)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (STRINGLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetEnvAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETPARAM)
    (C-TYPES:DEFUN-DLL
        SQLSETPARAM
        ((STATEMENTHANDLE SQLHSTMT)
            (PARAMETERNUMBER SQLUSMALLINT)
            (VALUETYPE SQLSMALLINT)
            (PARAMETERTYPE SQLSMALLINT)
            (LENGTHPRECISION SQLUINTEGER)
            (PARAMETERSCALE SQLSMALLINT)
            (PARAMETERVALUE SQLPOINTER)
            (STRLEN_OR_IND (SQLINTEGER *)))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetParam"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETSTMTATTR)
    (C-TYPES:DEFUN-DLL
        SQLSETSTMTATTR
        ((STATEMENTHANDLE SQLHSTMT)
            (ATTRIBUTE SQLINTEGER)
            (VALUE SQLPOINTER)
            (STRINGLENGTH SQLINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetStmtAttr"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSETSTMTOPTION)
    (C-TYPES:DEFUN-DLL
        SQLSETSTMTOPTION
        ((STATEMENTHANDLE SQLHSTMT)
            (OPTION SQLUSMALLINT)
            (VALUE SQLUINTEGER))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSetStmtOption"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSPECIALCOLUMNS)
    (C-TYPES:DEFUN-DLL
        SQLSPECIALCOLUMNS
        ((STATEMENTHANDLE SQLHSTMT)
            (IDENTIFIERTYPE SQLUSMALLINT)
            (CATALOGNAME (SQLCHAR *))
            (NAMELENGTH1 SQLSMALLINT)
            (SCHEMANAME (SQLCHAR *))
            (NAMELENGTH2 SQLSMALLINT)
            (TABLENAME (SQLCHAR *))
            (NAMELENGTH3 SQLSMALLINT)
            (SCOPE SQLUSMALLINT)
            (NULLABLE SQLUSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLSpecialColumns"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLSTATISTICS)
    (C-TYPES:DEFUN-DLL
        SQLSTATISTICS
        ((STATEMENTHANDLE SQLHSTMT)
            (CATALOGNAME (SQLCHAR *))
            (NAMELENGTH1 SQLSMALLINT)
            (SCHEMANAME (SQLCHAR *))
            (NAMELENGTH2 SQLSMALLINT)
            (TABLENAME (SQLCHAR *))
            (NAMELENGTH3 SQLSMALLINT)
            (UNIQUE SQLUSMALLINT)
            (RESERVED SQLUSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLStatistics"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLTABLES)
    (C-TYPES:DEFUN-DLL
        SQLTABLES
        ((STATEMENTHANDLE SQLHSTMT)
            (CATALOGNAME (SQLCHAR *))
            (NAMELENGTH1 SQLSMALLINT)
            (SCHEMANAME (SQLCHAR *))
            (NAMELENGTH2 SQLSMALLINT)
            (TABLENAME (SQLCHAR *))
            (NAMELENGTH3 SQLSMALLINT)
            (TABLETYPE (SQLCHAR *))
            (NAMELENGTH4 SQLSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLTables"
        :LINKAGE-TYPE
        :PASCAL)
    (EXPORT 'SQLTRANSACT)
    (C-TYPES:DEFUN-DLL
        SQLTRANSACT
        ((ENVIRONMENTHANDLE SQLHENV)
            (CONNECTIONHANDLE SQLHDBC)
            (COMPLETIONTYPE SQLUSMALLINT))
        :RETURN-TYPE
        SQLRETURN
        :LIBRARY-NAME
        "ODBC32.dll"
        :ENTRY-NAME
        "SQLTransact"
        :LINKAGE-TYPE
        :PASCAL))
(PROVIDE "ODBC-FFI")
