//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CormanLisp.rc
//

#define IDB_BITMAP2                     106
#define IDB_SPLASH_301                  106
#define IDD_DIALOG1                     128
#define IDD_BROWSER                     129
#define IDD_LEGAL                       130
#define IDD_PREFERENCES                 131
#define IDR_LISPSTATUS                  132
#define IDD_VIEW_LISP_HEAP              133
#define IDD_PAGE_SETUP_DIALOG           136
#define IDD_ABOUTBOX                    137
#define IDD_SPLASH                      138
#define IDD_CREDITS                     140
#define IDD_GOTO_LINE                   141
#define IDD_VIEW_LISPVARS               142
#define IDC_SPLASH                      200
#define IDB_CCLLOGO                     201
#define IDB_CCLLOGO_SMALLER             202
#define IDS_INVALID_MEASUREMENT         300
#define IDS_MEASUREMENT_RANGE           301
#define IDR_HTMLTYPE                    302
#define IDR_HTMLTYPE2                   303
#define IDS_FINISHED_SEARCH             304
#define IDS_TITLE_FORMATBAR             305
#define IDS_TITLE_TOOLBAR               306
#define IDS_INCH1_ABBREV                307
#define IDS_INCH2_ABBREV                308
#define IDS_INCH3_ABBREV                309
#define IDS_INCH4_ABBREV                310
#define IDS_CM_ABBREV                   311
#define IDS_POINT_ABBREV                312
#define IDS_PICA_ABBREV                 313
#define IDS_INDICATOR_LINE_NUMBER       314
#define IDS_LEGALSTRING                 315
#define IDS_INDICATOR_COLUMN_NUMBER     316
#define IDR_LISPVIEW_CONTEXT            400
#define IDR_MAINFRAME                   500
#define IDR_BROWSERFRAME                501
#define IDR_BROWSERFRAME1               502
#define IDR_LISPSOURCETYPE1             503
#define IDR_LISPSOURCETYPE2             504
#define IDR_TEXTTYPE                    505
#define IDC_LIST1                       1000
#define IDC_EDITREGCODE                 1005
#define IDC_REGVERSION                  1006
#define IDC_DAYSREMAINING               1007
#define IDC_ABOUTNAME                   1008
#define IDC_ABOUTORG                    1009
#define IDC_EVALMESSAGE                 1010
#define IDC_LEGALTEXT                   1012
#define IDC_PREFS_AUTO_INDENT           1100
#define IDC_PREFS_PAREN_MATCHING        1101
#define IDC_PREFS_PROT_MOUSE_MOVE       1102
#define IDC_PREFS_PROT_KEY_DOWN         1103
#define IDC_PREFS_APPEND_LISP_OUTPUT    1104
#define IDC_FONT_NAME                   1105
#define IDC_SELECT_FONT                 1106
#define IDC_PREFS_BOLD                  1107
#define IDC_PREFS_ITALIC                1108
#define IDC_TEXTCOLOR                   1109
#define IDC_HIGHLIGHTTEXTCOLOR          1111
#define IDC_OUTPUTTEXTCOLOR             1112
#define IDC_TAB                         1113
#define IDC_CHAR_SIZE                   1114
#define IDC_RESTORE                     1115
#define IDC_HINTBACKGROUNDCOLOR         1116
#define IDC_REPLACE_TABS_WITH_SPACES    1117
#define IDC_FULL_PATH_IN_TITLE          1120
#define IDC_PREFS_PAREN_MATCHING2       1120
#define IDC_REMEMBER_OPEN_DOCUMENTS     1121
#define IDC_REMEMBER_DOCUMENT_POSITIONS 1122
#define IDC_AUTO_COLORIZE               1123
#define IDC_FULL_PATH_IN_TITLE2         1123
#define IDC_LISPHEAP_0                  1200
#define IDC_LISPHEAP_1                  1201
#define IDC_LISPHEAP_2                  1202
#define ID_LISPHEAP_0                   1203
#define ID_LISPHEAP_1                   1204
#define ID_LISPHEAP_2                   1205
#define IDC_EDIT_BM                     1300
#define IDC_EDIT_LM                     1301
#define IDC_EDIT_RM                     1302
#define IDC_EDIT_TM                     1303
#define IDC_BOX                         1304
#define IDC_GOTO_LINE_NUMBER            1400
#define IDC_URL_NAME                    1500
#define ID_HELP_LICENSEAGREEMENT        33000
#define ID_HELP_CREDITS                 33001
#define ID_HELP_CORMANLISPCOM           33002
#define ID_VIEW_LISP_HEAP               33003
#define ID_WEB_BROWSE                   33004
#define ID_CREDITS                      33006
#define ID_CORMAN_NET                   33007
#define ID_HINTBACKGROUNDCOLOR          33008
#define ID_HIGHLIGHTTEXTCOLOR           33009
#define ID_OUTPUTTEXTCOLOR              33010
#define ID_TEXTCOLOR                    33011
#define ID_VIEW_SELECTION               33012
#define ID_EXECUTE_FILE                 33013
#define ID_PAGE_SETUP                   33014
#define ID_EXECUTESELECTION             33015
#define ID_PREFERENCES                  33016
#define ID_HELP_CCL_DOC                 33017
#define ID_GOTO_LINE                    33018
#define ID_REGISTRATION                 33019
#define ID_WINDOW_CLOSEALLDOCUMENTS     33020
#define ID_GO_BACK                      33100
#define ID_GO_FORWARD                   33101
#define ID_GO_HOME                      33102
#define ID_GO_SEARCH                    33103
#define ID_VIEW_REFRESH                 33104
#define ID_VIEW_STOP                    33105
#define ID_VIEW_SOURCE                  33106
#define ID_VIEW_OPTIONS                 33107
#define ID_FILE_PAGE                    33108
#define ID_VIEW_LISPVARS                33109
#define ID_VIEW_LISPVARS_TEXT           33110
#define ID_VIEW_LISPVARIABLES           33111

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
